apiVersion: v1
kind: Service
metadata:
  name: catalogue
  labels:
    app: catalogue
spec:
  selector:
    app: catalogue
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080